%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                              %
% The following preamble was originally written by the CSE 379 course staff at %
% the University at Buffalo as a template for lab documentation.               %
%                                                                              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{docs}[2017/05/06 Class for writing documentation and reports]
\LoadClass[10pt]{article}

\oddsidemargin=0.0cm
\textwidth=16.5cm
\textheight=22.8cm
\topmargin=-1.0cm

\RequirePackage[utf8]{inputenc}

\RequirePackage{multirow}
\RequirePackage{tabularx}

\RequirePackage[hidelinks]{hyperref}

\RequirePackage{mathtools}% Loads amsmath

\RequirePackage{graphicx}
\RequirePackage{float}

\RequirePackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{1pt}

\RequirePackage{indentfirst}


